[project]
name = "team2-ecommerce-fast-api"
version = "0.1.0"
description = ""
authors = [
    {name = "Géraldine François",email = "145096426+GeraldineFrancois@users.noreply.github.com"}
]
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.135.1,<0.136.0)",
    "uvicorn[standard] (>=0.41.0,<0.42.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "sqlalchemy (>=2.0.48,<3.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "sqlmodel (>=0.0.37,<0.0.38)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "bcrypt (>=3.2.2,<4.0.0)",
    "email-validator (>=2.1.0,<3.0.0)"
]

[tool.poetry]
name = "team2-ecommerce-fast-api"
version = "0.1.0"
description = ""
authors = ["Géraldine François <145096426+GeraldineFrancois@users.noreply.github.com>"]
packages = [{include = "app"}]

[tool.black]
target-version = ["py311"]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --strict-markers"

[tool.coverage.run]
source = ["app"]
omit = ["*/tests/*", "*/__pycache__/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.3.0,<27.0.0)",
    "mypy (>=1.19.1,<2.0.0)",
    "coverage (>=7.13.4,<8.0.0)",
    "types-python-jose (>=3.3.4,<4.0.0)",
    "types-passlib (>=1.7.7,<2.0.0)"
]
